name: Test Create Issue on Failure

on:
  push:
    branches:
      - main

permissions:
  issues: write
  actions: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Step A
        if: always()
        run: exit 1

      - name: Step B
        if: always()
        run: echo "Step B passed"

      - name: Step C
        if: always()
        run: exit 1

      - if: failure()
        uses: DmitriyLewen/create-issue-on-failure@ad0c7801ebac9a06424f4b072603b92339e349cd
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
