name: Test Create Issue on Failure

on:
  push:
    branches:
      - main

permissions:
  issues: write
  actions: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Step A
        if: always()
        run: echo "Step A passed"

      - name: Step B
        if: always()
        run: exit 1

      - name: Step C
        if: always()
        run: exit 1

      - if: failure()
        uses: DmitriyLewen/create-issue-on-failure@d4c648915a11ac60a9bbe0d8ff7caf7db500c7c5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
